### ISSUE TITLE
Set up research@magmo.com as a shared email

### ISSUE THREAD

**Issue by wunnaii** [magmo/magmo.com#15]
Email is a private way to communicate that allows external parties to provide inquiry details. 
A shared email would be best to manage this type of communication, and provide all team members access.

Currently, the email used on magmo.com is research@magmo.com

**Comment by geoknee** [comment]
I set this up to forward to @andrewgordstewart (for now).

**Comment by geoknee** [comment]
It might mean a bit of spam, I guess 😬

**Comment by NiloCK** [comment]
> It might mean a bit of spam, I guess grimacing

For example, the test email I just sent there.

**Comment by andrewgordstewart** [comment]
as long as we can filter the email separate from the inbox, this is 👍
